# Preserve the original farm CLASS calculation. The committed fixture generated
# by this script is authoritative and is not regenerated by the test suite.
using Printf
using PyCall

const K_GRID = 10.0 .^ range(log10(5.0e-6), log10(100.0); length=300)
const NAMES = ["z", "ln10As", "ns", "H0", "ombh2", "omch2", "Mν", "w0", "wa"]
const VALUES = [0.8, 3.044, 0.965, 67.4, 0.0224, 0.12, 0.06, -1.0, 0.0]
const PARAMETERS = Dict(NAMES .=> VALUES)

function main()
    p = PARAMETERS
    h = p["H0"] / 100
    classy = pyimport("classy")
    cosmology = classy.Class()
    try
        cosmology.set(Dict(
            "output" => "mPk",
            "P_k_max_h/Mpc" => 100.0 / h,
            "z_pk" => "0.0,5.0",
            "h" => h,
            "omega_b" => p["ombh2"],
            "omega_cdm" => p["omch2"],
            "ln10^{10}A_s" => p["ln10As"],
            "n_s" => p["ns"],
            "tau_reio" => 0.0568,
            "N_ur" => 2.033,
            "N_ncdm" => 1,
            "m_ncdm" => p["Mν"],
            "use_ppf" => "yes",
            "w0_fld" => p["w0"],
            "wa_fld" => p["wa"],
            "fluid_equation_of_state" => "CLP",
            "cs2_fld" => 1.0,
            "Omega_Lambda" => 0.0,
            "Omega_scf" => 0.0,
        ))
        cosmology.compute()
        open(joinpath(@__DIR__, "reference_outputs.txt"), "w") do stream
            println(stream, "# Original farm CLASS linear spectra in physical units")
            println(stream, "# z=0.8 ln10As=3.044 ns=0.965 H0=67.4 ombh2=0.0224 omch2=0.12 Mnu=0.06 w0=-1 wa=0")
            println(stream, "# k_Mpc^-1 Pmm_Mpc^3 Pcb_Mpc^3")
            for k in K_GRID
                pmm = Float64(cosmology.pk_lin(k, p["z"]))
                pcb = Float64(cosmology.pk_cb_lin(k, p["z"]))
                @printf(stream, "%.17g %.17g %.17g\n", k, pmm, pcb)
            end
        end
    finally
        try
            cosmology.struct_cleanup()
            cosmology.empty()
        catch
        end
    end
end

main()

